apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: sso
  labels:
    app: sso
    role: backend
data:
  db-user: "cG9zdGdyZXM="
  db-password: "UEBzc3cwcmQ="
  db-name: "a2V5Y2xvYWs="
