apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: keycloak-hpa
  namespace: sso
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: keycloak
  metrics:
  - type: Resource
    resource:
      name: cpu
      target: 
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue 
        averageValue: 2048Mi
